const translations = {
    fr: {
        // Welcome Screen
        language: "Langue",

        // Sidebar & Top Bar
        back: "Retour",
        home: "Accueil",
        notifications: "Notifications",
        albums: "Albums",
        albumsBeats: "Albums Beats",
        videos: "Vidéos",
        bonus: "Bonus",
        likedTitles: "Titres Likés",
        library: "Bibliothèque",
        about: "À propos",
        about_mmg_music: "Mmg Music est un projet musical proposant des compositions de styles variés, avec des influences allant de la pop à l'électro, souvent inspirées par l'univers des jeux vidéo. Découvrez un univers riche en mélodies et en émotions.",
        about_mmg_beats: "Mmg Beats est le versant hip-hop et trap du projet. Retrouvez ici des instrumentales percutantes et des productions pour artistes, disponibles sur toutes les plateformes de streaming.",
        guide: "Guides",
        searchPlaceholder: "Titre, tag, album...",
        search: "Rechercher",
        shop: "Boutique",
        achievements: "Succès",
        settings: "Paramètres",
        wifi: "WiFi",
        filterByTag: "Filtrer par tag",
        nextTrack: "Titre Suivant",

        // Dashboard
        recommendedPlaylists: "Playlists Recommandées",
        featured: "À la une",
        news: "Actualités",
        queueTitle: "En file d'attente",
        recentlyPlayed: "Récemment écouté",
        listenNow: "Écouter",
        viewDetails: "Voir Détails",
        lastRelease: "Dernière Sortie",
        nextRelease: "Prochaine Sortie",
        socials: "Réseaux",

        // Player
        randomPlayback: "Lecture aléatoire",
        previous: "Précédent",
        next: "Suivant",
        repeatSong: "Répéter la chanson",
        volume: "Volume",
        likeSong: "Aimer la chanson",
        addPlaylist: "Playlist",
        shareSong: "Partager la chanson",
        showHidePlayer: "Afficher/Masquer le lecteur",
        noTrackPlaying: "Aucun titre en lecture",
        noTrackPlaying: "Aucun titre en lecture",
        linkCopied: "Lien copié dans le presse-papiers !",
        copyFailed: "La copie a échoué.",
        playFromDetailsNeeded: "Veuillez lancer le contenu en cliquant directement sur le lecteur YouTube.",

        // Cards & Sections
        titles: "Titres",
        toggleView: "Changer de vue",
        like: "Aimer",
        removeLike: "Ne plus aimer",
        removePlaylist: "Playlist",
        listenToTitle: "Écouter le titre",
        viewAlbum: "Voir l'album",
        musicTitle: "Titre musical",
        videoOrMakingOf: "Vidéo / Making-of",
        viewContent: "Voir le contenu",
        workInProgress: "Contenu en préparation...",
        playlist: "Playlist",
        noResults: "Aucun résultat trouvé.",
        noLikedTitles: "Vous n'avez pas encore liké de titre.",
        playlistEmpty: "Votre playlist est vide.",
        currentPlaylist: "Ma Playlist",

        // Details Page
        album: "Album",
        year: "Année",
        inspirations: "Inspirations",
        tags: "Tags",
        listenOn: "Écouter sur",
        launchSong: "Lancer la chanson",
        addToPlaylist: "Ajout playlist",
        addedToPlaylist: "Ajouté à la playlist",
        gameplayVideo: "Vidéo Gameplay",
        makingOfVideo: "Vidéo Making-Of",
        videoClip: "Clip",
        videoMakingOf: "Making Of",
        noAssociatedVideo: "Aucune vidéo associée.",
        videoLabel: "Vidéo",
        unknown: "Inconnu",

        // Settings & Overlays
        sfx: "Effets sonores (SFX)",
        connecting: "Connexion...",
        connectionSuccess: "Connecté avec succès !",
        moreOptions: "Options",
        share: "Partager",
        theme: "Mode Sombre",
        orientation: "Orientation",

        // Shop & Achievements
        shopThemes: "Thèmes",
        theme_default: "Défaut",
        theme_default_desc: "Le style original et épuré de Mmg Studio.",
        theme_16bit: "Frutiger Aero",
        theme_16bit_desc: "Un style brillant, vibrant et nostalgique (années 2000).",
        theme_spotimon: "Spotimon",
        theme_spotimon_desc: "Un style inspiré des jeux Pokémon sur DS.",
        DS: "DS",
        theme_default_2: "Default 2",
        theme_default_2_desc: "Un thème moderne et épuré avec une typographie élégante.",
        theme_playstation: "Playstation",
        theme_playstation_desc: "L'interface XMB légendaire avec ses vagues apaisantes.",
        theme_music_studio: "Music Studio",
        theme_music_studio_desc: "Une interface technique inspirée des plugins audio VST.",
        shopBackgrounds: "Arrière-plans",
        bg_bubbles: "Aurore Verte",
        bg_theme_default: "Défaut",
        bg_waves: "Nuit Étoilée", // Conservé pour la compatibilité, mais peut être renommé
        bg_digital: "Digital", // NOUVEAU
        bg_blurry_gradient: "Dégradé Flou",
        bg_icons: "Icônes",
        bg_blob: "Blob",
        select: "Sélectionner",
        selected: "Sélectionné",
        unlock: "Débloquer",
        unlockWithLockIcon: "<i class='fas fa-lock'></i> Débloquer",
        myCoins: "Mes Pièces",
        secretCode: "Code secret...",
        shopMissions: "Missions",
        shopAndRewards: "Boutique & Succès",
        missionCompleted: "Terminé",
        activate: "Activer",
        achievementUnlocked: "Succès déverrouillé",
        allAchievementsUnlocked: "Tous les succès ont été déverrouillés !",
        allSongsUnlocked: "Tous les morceaux ont été débloqués !",
        incorrectCode: "Code incorrect.",
        achievement_loopMaster_title: "Maître de la boucle",
        confirmPurchase: "Confirmer l'achat",
        confirm: "Confirmer",
        cancel: "Annuler",
        purchaseMessage: "Voulez-vous vraiment acheter <strong>{itemName}</strong> pour {itemCost} <svg width='1em' height='1em' viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg' class='coin-icon-svg' style='display: inline-block; vertical-align: middle;'><circle cx='50' cy='50' r='44' fill='none' stroke='currentColor' stroke-width='8' /><path d='M 33.5 64 L 25 64 L 25 45 Q 25 41 27 38 Q 28.5 35 32 33.5 Q 35.5 32 39 32 Q 42 32 45 33.5 Q 48 35 50 38 Q 52 35 55 33.5 Q 58 32 61.5 32 Q 65.5 32 68.5 33.5 Q 71.5 35 73.5 38 Q 75 41 75 45 L 75 64 L 66.5 64 L 66.5 45 Q 66.5 42.5 65 41 Q 63.5 39.5 61 39.5 Q 58.5 39.5 57 41 Q 55.5 42.5 55.5 45 L 55.5 64 L 44.5 64 L 44.5 45 Q 44.5 42.5 43 41 Q 41.5 39.5 39 39.5 Q 36.5 39.5 35 41 Q 33.5 42.5 33.5 45 L 33.5 64 Z' fill='currentColor' /></svg> ?",
        purchaseSuccess: "Achat réussi !",
        themeUnlocked: "Débloqué",
        yourCoins: "Vos pièces : {userCoins} <svg width='1em' height='1em' viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg' class='coin-icon-svg' style='display: inline-block; vertical-align: middle;'><circle cx='50' cy='50' r='44' fill='none' stroke='currentColor' stroke-width='8' /><path d='M 33.5 64 L 25 64 L 25 45 Q 25 41 27 38 Q 28.5 35 32 33.5 Q 35.5 32 39 32 Q 42 32 45 33.5 Q 48 35 50 38 Q 52 35 55 33.5 Q 58 32 61.5 32 Q 65.5 32 68.5 33.5 Q 71.5 35 73.5 38 Q 75 41 75 45 L 75 64 L 66.5 64 L 66.5 45 Q 66.5 42.5 65 41 Q 63.5 39.5 61 39.5 Q 58.5 39.5 57 41 Q 55.5 42.5 55.5 45 L 55.5 64 L 44.5 64 L 44.5 45 Q 44.5 42.5 43 41 Q 41.5 39.5 39 39.5 Q 36.5 39.5 35 41 Q 33.5 42.5 33.5 45 L 33.5 64 Z' fill='currentColor' /></svg>",
        notEnoughCoins: "Vous n'avez pas assez de pièces !",
        achievement_loopMaster_desc: "Écouter 3 fois de suite le même titre en boucle.",
        achievement_retroPlayer_title: "Joueur Rétro",
        achievement_retroPlayer_desc: "Écouter 3 titres de la catégorie 'Rétro'.",
        achievement_patienceIsKey_title: "La patience est une vertu",
        achievement_patienceIsKey_desc: "Attendre la fin de la connexion WiFi.",
        achievement_spotimonFan_title: "Fan de Spotimon",
        achievement_spotimonFan_desc: "Écouter tous les titres de la série 'Spotimon'.",
        achievement_doubleScreen_title: "Double Screen",
        achievement_doubleScreen_desc: "Écouter 1 titre de chaque profil.",
        achievement_dailyBonusMaster_title: "Maître du Bonus",
        achievement_dailyBonusMaster_desc: "Atteindre une série de 7 jours de bonus quotidien.",
        unlockThemeMission: "Pour débloquer ce thème, terminez la mission :",
        finishMission: "Pour débloquer, terminez la mission :",
        completeMission: "Terminer la mission :",
        unlockWithCoins: "Cet article peut être acheté pour {cost} pièces.",
        buyToUnlock: "Acheter pour débloquer",
        unlockBackgroundWithCoins: "Vous pouvez débloquer un nouvel arrière-plan pour {cost} pièces.",
        unlockTrackWithCoins: "Vous pouvez débloquer un nouveau titre pour {COIN_COST_UNLOCK} pièces.",
        achievement_psPlayer_title: "Joueur PlayStation",
        achievement_psPlayer_desc: "Écouter 2 titres de la catégorie 'PlayStation'.",
        achievement_pwaInstall_title: "App Installée",
        achievement_pwaInstall_desc: "Installer l'application Mmg Studio sur votre appareil.",
        unreadContent: "Vous avez du contenu non lu.",

        // Notifications & Dialogs
        titleAddedPlaylist: "Titre ajouté à votre playlist !",
        titleRemovedPlaylist: "Titre retiré de votre playlist.",
        devMessageTitle: "Message du développeur",
        playlistCleared: "Playlist vidée.",
        playlistSaved: "Playlist sauvegardée dans la bibliothèque !",
        unlockAvailableTitle: "Déblocage disponible !",
        unlockAvailableDesc: "Vous avez assez de pièces pour débloquer un nouveau contenu exclusif.",
        updateLog: "Journal des mises à jour",
        markAsRead: "Marquer comme lu",
        trackLocked: "Ce titre est verrouillé. Débloquez-le dans la boutique d'albums !",
        youUnlocked: "Vous avez débloqué",
        allTracksUnlocked: "Tous les titres de cet album sont déjà débloqués.",
        needCoinsToUnlock: "Vous avez besoin de {COIN_COST_UNLOCK} pièces pour débloquer un titre.",
        trackToUnlock_one: "{count} titre à débloquer",
        trackToUnlock_many: "{count} titres à débloquer",
        availableInAlbum: "Disponible dans l'album : {albumTitle}",

        // PWA
        pwaInstallTitle: "Installer l'application Mmg Studio",
        pwaInstallDescription: "Pour une expérience optimale, installez l'application sur votre appareil. C'est rapide, léger et ne prend que peu de place.",
        pwaInstallBenefits: "Avantages :",
        pwaBenefit1: "Accès rapide et direct depuis votre écran d'accueil.",
        pwaBenefit2: "Badge de notification sur l'icône pour les nouveautés.",
        pwaBenefit3: "Interface optimisée pour une expérience mobile fluide.",
        pwaInstall: "Installer",
        pwaDismiss: "Plus tard",

        // Guide
        guideChoice: "Choisir un guide",
        guideMain: "1. Navigation & Interface",
        guideMusic: "2. Sections du Site",
        guide_desc_nav: "Petit tour d'horizon de l'interface.",
        guide_desc_pages: "Explorons ensemble les pages et le contenu du site.",

        // Playlist & Queue
        playPlaylist: "Lancer la playlist",
        savePlaylist: "Enregistrer la playlist",
        clearPlaylist: "Vider la playlist",
        deleteFromPlaylist: "Supprimer de la playlist",
        playNext: "Lire après",
        queue: "File d'attente",
        viewMore: "Voir plus",
        addedToQueue: "ajouté à la file d'attente",
        addToQueue: "Ajout file d'attente",
        removeFromQueue: "Retirer de la file d'attente",
        queueEmpty: "Aucun contenu écouté récemment.",
        nowPlayingFrom: "Lecture en cours depuis :",
        fromTitles: "depuis les titres",
        fromMyPlaylist: "depuis ma playlist",
        fromPlaybackQueue: "depuis la file d'attente",
        fromLiked: "depuis les titres likés",
        fromVideos: "depuis les vidéos",
        fromMmgPlaylists: "depuis les playlists Mmg",
        fromSearch: "depuis la recherche",

        // Search & Filter
        searchFor: "Recherche de",
        contentWithTag: "Contenu avec le tag",
        searchResults: "Résultats de recherche",
        titleAndArtist: "Titre & Artiste",

        // Daily Bonus (FR)
        dailyBonus: "Bonus Quotidien : +{count} pièce(s) ! Série de {streak} jour(s).",
        dailyBonusUnlock: "Bonus Jour 7 ! Vous avez débloqué le titre : {title}",
        dailyBonusAllTracksUnlocked: "Félicitations ! Vous avez débloqué tous les titres exclusifs !",
        dailyBonusFinalTheme: "Merci pour votre fidélité !",
        dailyBonusTitle: "Bonus Quotidien",
        day: "Jour",
        specialReward: "Spécial",
        claimBonus: "Récupérer le Bonus",
        dailyBonusStreakText: "Revenez demain pour continuer votre série !",
        dailyBonusStartText: "Connectez-vous chaque jour pour gagner des récompenses !",
        dailyBonusNextRewardSpecial: "Revenez demain pour la récompense spéciale !",
        dailyBonusAvailable: "Une récompense quotidienne vous attend !",
        dailyBonusAlreadyClaimed: "À demain !",
        dailyBonusReceived: "Reçu :",
        dailyBonusCoins: "Pièces",
        dailyBonusStreak: "Série :",
        dailyBonusToWin: "À gagner :",
        dailyBonusExclusiveTrack: "Titre Exclusif",

        // NOUVEAU: Avertissement pour le mode mobile sur PC
        desktopWarningTitle: "Mode Mobile Activé",
        desktopWarningMessage1: "Cette vue est optimisée pour les appareils mobiles et les contrôles gestuels.",
        desktopWarningMessage2: "Vous risquez d'être bloqué en utilisant un ordinateur.",
        desktopWarningCTA: "Agrandissez la fenêtre de votre navigateur pour repasser en mode ordinateur et profiter d'une expérience optimale.",
        upcomingTitle: "Prochaine Sortie",
        upcomingBadge: "Bientôt",
        upcomingDesc: "Préparez-vous pour une nouvelle aventure musicale dans le désert ! Ce titre aux sonorités rétro et entraînantes vous transportera dans un niveau de jeu de plateforme classique.",
        comingSoon: "Bientôt disponible",

        // New keys
        display: "Affichage",
        listView: "Affichage",
        playlistChillName: "Chill Game Music",
        playlistChillSubtitle: "Sélection personnalisée",
        playlistFrutigerName: "Frutiger Aero",
        playlistFrutigerSubtitle: "Beats instrumentaux",
        claim: "Réclamer",
        bonusClaimed: "Bonus récupéré",
        viewDesktop: "Mode PC",
        viewMobile: "Mode Mobile",
    },

    en: {
        // Welcome Screen
        language: "Language",

        // Sidebar & Top Bar
        back: "Back",
        home: "Home",
        notifications: "Notifications",
        albums: "Albums",
        albumsBeats: "Beats Albums",
        videos: "Videos",
        bonus: "Bonus",
        likedTitles: "Liked Titles",
        library: "Library",
        about: "About",
        about_mmg_music: "Mmg Music is a musical project offering compositions in various styles, with influences ranging from pop to electronic music, often inspired by the world of video games. Discover a universe rich in melodies and emotions.",
        about_mmg_beats: "Mmg Beats is the hip-hop and trap side of the project. Find hard-hitting instrumentals and productions for artists here, available on all streaming platforms.",
        guide: "Guides",
        searchPlaceholder: "Title, tag, album...",
        search: "Search",
        shop: "Shop",
        achievements: "Achievements",
        settings: "Settings",
        wifi: "WiFi",
        filterByTag: "Filter by Tag",
        nextTrack: "Next Track",

        // Dashboard
        recommendedPlaylists: "Recommended Playlists",
        featured: "Featured",
        news: "News",
        queueTitle: "Playback Queue",
        recentlyPlayed: "Recently Played",
        listenNow: "Listen",
        viewDetails: "View Details",
        lastRelease: "Last release",
        nextRelease: "Upcoming",
        socials: "Socials",

        // Player
        randomPlayback: "Shuffle",
        previous: "Previous",
        next: "Next",
        repeatSong: "Repeat Song",
        volume: "Volume",
        likeSong: "Like Song",
        addPlaylist: "Playlist",
        shareSong: "Share Song",
        showHidePlayer: "Show/Hide Player",
        noTrackPlaying: "No track playing",
        noTrackPlaying: "No track playing",
        linkCopied: "Link copied to clipboard!",
        copyFailed: "Copy failed.",
        playFromDetailsNeeded: "Please start the content by clicking directly on the YouTube player.",

        // Cards & Sections
        titles: "Tracks",
        toggleView: "Toggle View",
        like: "Like",
        removeLike: "Unlike",
        removePlaylist: "playlist",
        listenToTitle: "Listen to the track",
        viewAlbum: "View album",
        musicTitle: "Music Track",
        videoOrMakingOf: "Video / Making-Of",
        viewContent: "View content",
        workInProgress: "Content in preparation...",
        playlist: "Playlist",
        noResults: "No results found.",
        noLikedTitles: "You haven't liked any tracks yet.",
        playlistEmpty: "Your playlist is empty.",
        currentPlaylist: "My Playlist",

        // Details Page
        album: "Album",
        year: "Year",
        inspirations: "Inspirations",
        tags: "Tags",
        listenOn: "Listen on",
        launchSong: "Play Song",
        addToPlaylist: "Add to Playlist",
        addedToPlaylist: "Added to Playlist",
        gameplayVideo: "Gameplay Video",
        makingOfVideo: "Making-Of Video",
        videoClip: "Music Video",
        videoMakingOf: "Making Of",
        noAssociatedVideo: "No associated video.",
        videoLabel: "Video",
        unknown: "Unknown",

        // Settings & Overlays
        sfx: "Sound Effects (SFX)",
        connecting: "Connecting...",
        connectionSuccess: "Successfully connected!",
        moreOptions: "Options",
        share: "Share",
        theme: "Dark Mode",
        orientation: "Orientation",

        // Shop & Achievements
        shopThemes: "Themes",
        theme_default: "Default",
        theme_default_desc: "The original and clean style of Mmg Studio.",
        theme_16bit: "Frutiger Aero",
        theme_16bit_desc: "A glossy, vibrant, and nostalgic style (2000s).",
        theme_spotimon: "Spotimon",
        theme_spotimon_desc: "A style inspired by the DS Pokémon games.",
        DS: "DS",
        theme_default_2: "Default 2",
        theme_default_2_desc: "A modern and clean theme with elegant typography.",
        theme_playstation: "Playstation",
        theme_playstation_desc: "The legendary XMB interface with its soothing waves.",
        theme_music_studio: "Music Studio",
        theme_music_studio_desc: "A technical interface inspired by VST audio plugins.",
        shopBackgrounds: "Backgrounds",
        bg_bubbles: "Green Dawn",
        bg_theme_default: "Default",
        bg_waves: "Starry Night", // Kept for compatibility, can be renamed
        bg_digital: "Digital", // NEW
        bg_blurry_gradient: "Blurry Gradient",
        bg_icons: "Icons",
        bg_blob: "Blob",
        select: "Select",
        selected: "Selected",
        unlock: "Unlock",
        unlockWithLockIcon: "<i class='fas fa-lock'></i> Unlock",
        myCoins: "My Coins",
        secretCode: "Secret code...",
        shopMissions: "Missions",
        shopAndRewards: "Shop & Rewards",
        missionCompleted: "Completed",
        activate: "Activate",
        achievementUnlocked: "Achievement Unlocked",
        allAchievementsUnlocked: "All achievements have been unlocked!",
        allSongsUnlocked: "All songs have been unlocked!",
        incorrectCode: "Incorrect code.",
        achievement_loopMaster_title: "Loop Master",
        confirmPurchase: "Confirm Purchase",
        confirm: "Confirm",
        cancel: "Cancel",
        purchaseMessage: "Do you really want to buy <strong>{itemName}</strong> for {itemCost} <svg width='1em' height='1em' viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg' class='coin-icon-svg' style='display: inline-block; vertical-align: middle;'><circle cx='50' cy='50' r='44' fill='none' stroke='currentColor' stroke-width='8' /><path d='M 33.5 64 L 25 64 L 25 45 Q 25 41 27 38 Q 28.5 35 32 33.5 Q 35.5 32 39 32 Q 42 32 45 33.5 Q 48 35 50 38 Q 52 35 55 33.5 Q 58 32 61.5 32 Q 65.5 32 68.5 33.5 Q 71.5 35 73.5 38 Q 75 41 75 45 L 75 64 L 66.5 64 L 66.5 45 Q 66.5 42.5 65 41 Q 63.5 39.5 61 39.5 Q 58.5 39.5 57 41 Q 55.5 42.5 55.5 45 L 55.5 64 L 44.5 64 L 44.5 45 Q 44.5 42.5 43 41 Q 41.5 39.5 39 39.5 Q 36.5 39.5 35 41 Q 33.5 42.5 33.5 45 L 33.5 64 Z' fill='currentColor' /></svg>?",
        purchaseSuccess: "Purchase successful!",
        themeUnlocked: "Unlocked",
        yourCoins: "Your coins: {userCoins} <svg width='1em' height='1em' viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg' class='coin-icon-svg' style='display: inline-block; vertical-align: middle;'><circle cx='50' cy='50' r='44' fill='none' stroke='currentColor' stroke-width='8' /><path d='M 33.5 64 L 25 64 L 25 45 Q 25 41 27 38 Q 28.5 35 32 33.5 Q 35.5 32 39 32 Q 42 32 45 33.5 Q 48 35 50 38 Q 52 35 55 33.5 Q 58 32 61.5 32 Q 65.5 32 68.5 33.5 Q 71.5 35 73.5 38 Q 75 41 75 45 L 75 64 L 66.5 64 L 66.5 45 Q 66.5 42.5 65 41 Q 63.5 39.5 61 39.5 Q 58.5 39.5 57 41 Q 55.5 42.5 55.5 45 L 55.5 64 L 44.5 64 L 44.5 45 Q 44.5 42.5 43 41 Q 41.5 39.5 39 39.5 Q 36.5 39.5 35 41 Q 33.5 42.5 33.5 45 L 33.5 64 Z' fill='currentColor' /></svg>",
        notEnoughCoins: "You don't have enough coins!",
        achievement_loopMaster_desc: "Listen to the same track 3 times in a row on loop.",
        achievement_retroPlayer_title: "Retro Player",
        achievement_retroPlayer_desc: "Listen to 3 tracks from the 'Retro' category.",
        achievement_patienceIsKey_title: "Patience is a Virtue",
        achievement_patienceIsKey_desc: "Wait for the WiFi connection to finish.",
        achievement_spotimonFan_title: "Spotimon Fan",
        achievement_spotimonFan_desc: "Listen to all tracks from the 'Spotimon' series.",
        achievement_doubleScreen_title: "Double Screen",
        achievement_doubleScreen_desc: "Listen to 1 track from each profile.",
        achievement_dailyBonusMaster_title: "Bonus Master",
        achievement_dailyBonusMaster_desc: "Reach a 7-day daily bonus streak.",
        unlockThemeMission: "To unlock this theme, complete the mission:",
        finishMission: "To unlock, complete the mission:",
        completeMission: "Complete mission:",
        unlockWithCoins: "This item can be purchased for {cost} coins.",
        buyToUnlock: "Buy to unlock",
        unlockBackgroundWithCoins: "You can unlock a new background for {cost} coins.",
        unlockTrackWithCoins: "You can unlock a new track for {COIN_COST_UNLOCK} coins.",
        achievement_psPlayer_title: "PlayStation Player",
        achievement_psPlayer_desc: "Listen to 2 tracks from the 'PlayStation' category.",
        achievement_pwaInstall_title: "App Installed",
        achievement_pwaInstall_desc: "Install the Mmg Studio app on your device.",
        unreadContent: "You have unread content.",

        // Notifications & Dialogs
        titleAddedPlaylist: "Track added to your playlist!",
        titleRemovedPlaylist: "Track removed from your playlist.",
        devMessageTitle: "Message from the developer",
        playlistCleared: "Playlist cleared.",
        playlistSaved: "Playlist saved to library!",
        unlockAvailableTitle: "Unlock Available!",
        unlockAvailableDesc: "You have enough coins to unlock new exclusive content.",
        updateLog: "Update Log",
        markAsRead: "Mark as read",
        trackLocked: "This track is locked. Unlock it in the album shop!",
        youUnlocked: "You unlocked",
        allTracksUnlocked: "All tracks in this album are already unlocked.",
        needCoinsToUnlock: "You need {COIN_COST_UNLOCK} coins to unlock a track.",
        trackToUnlock_one: "{count} track to unlock",
        trackToUnlock_many: "{count} tracks to unlock",
        availableInAlbum: "Available in album: {albumTitle}",

        // PWA
        pwaInstallTitle: "Install Mmg Studio App",
        pwaInstallDescription: "For the best experience, install the app on your device. It's fast, lightweight, and takes up very little space.",
        pwaInstallBenefits: "Benefits:",
        pwaBenefit1: "Faster and more direct access from your home screen.",
        pwaBenefit2: "Notification badge on the icon for new releases.",
        pwaBenefit3: "Optimized interface for a smooth mobile experience.",
        pwaInstall: "Install",
        pwaDismiss: "Later",

        // Guide
        guideChoice: "Choose a guide",
        guideMain: "1. Navigation & Interface",
        guideMusic: "2. Site Sections",
        guide_desc_nav: "A quick tour of the interface.",
        guide_desc_pages: "Let's explore the site's pages and content together.",

        // Playlist & Queue
        playPlaylist: "Play Playlist",
        savePlaylist: "Save Playlist",
        clearPlaylist: "Clear Playlist",
        deleteFromPlaylist: "Delete from playlist",
        playNext: "Play Next",
        queue: "Queue",
        viewMore: "View more",
        addedToQueue: "added to the queue",
        addToQueue: "Add to Queue",
        removeFromQueue: "Remove from Queue",
        fromTitles: "from tracks",
        fromMyPlaylist: "from my playlist",
        fromPlaybackQueue: "from queue",
        fromLiked: "from liked songs",
        fromVideos: "from videos",
        fromMmgPlaylists: "from Mmg Playlists",
        queueEmpty: "No recently streamed content.",
        nowPlayingFrom: "Now playing from:",
        fromSearch: "from search",

        // Search & Filter
        searchFor: "Search for",
        contentWithTag: "Content with tag",
        searchResults: "Search Results",

        // New additions
        listView: "Display",
        grid: "Grid",
        list: "List",
        instrumentals: "Instrumentals",
        titleAndArtist: "Title & Artist",
        fullscreen: "Fullscreen",

        // Track Descriptions (EN) - Should match data.json
        trackDescriptions: {
            "title7": "A pop composition inspired by recent Pokémon games, but with a touch that brings it closer to Japanese anime themes. The organic instrumentation evokes a romantic end-of-episode scene or a quiet night by a lake. Ultimately, it would fit perfectly in a Pokémon animated series!",
            "title1": "Inspired by the cheerful and catchy themes of Nintendo sports games, especially Wii Sports. Composed as an infinite loop, this track uses typical elements of the genre: calm drums, a piano melody, a marimba, and the iconic \"dooh\" voices found in many Nintendo titles!",
            "title2": "A sunny beach atmosphere with Latin percussion. This song is composed of a Part A and a Part B, with the B section featuring a small solo.",
            "title3": "Evokes the sound of menus and connection screens from the early 2000s. A Frutiger Aero-style composition, with sound effects that particularly recall the long loading times on old consoles!",
            "title4": "A classic shop theme, perfect for virtual shopping. The instrumentation and composition are inspired by the Wii eShop theme!",
            "title5": "A pop-oriented composition, a bit distant from Animal Crossing, but evoking a summer evening vibe. The main guitar and organic drums set a natural tone. The melody is completed by a heavily reverberated pluck, creating the track's warm atmosphere.",
            "title6": "This composition is reminiscent of the magical universe of Zelda games. The slightly mysterious and cheerful melody is composed of an enchanting bassline, with added elements like synths and pads. It feels like exploring a forest in Hyrule!",
            "title8": "A Frutiger Aero composition with a neo-soul piano. As the track progresses, the organic feel of the instruments transforms into a digital sound, with various synths replacing the piano!",
            "title9": "How many PS1, PS2, and other games from that era use DnB tracks, especially for racing games? A true old-school game must include this kind of music at least once in its OST. Inspired by Ridge Racer and others, this track is a tribute to vintage racing games.",
            "title10": "My interpretation of Wii's Rainbow Road. All the elements of the Mario Kart Wii soundtrack are here: a bassline similar to the menu, the piano as the main melody, and synths, brass, and guitar to spice up the composition. The track also includes the race start fanfare, the sound of the engine revving before the start, the lap sounds, the accelerated music on the final lap, and the final ranking music!",
            "title11": "As a big fan of Donkey Kong games and David Wise, this tribute was essential. Using the same instruments and music libraries as D. Wise, particularly those from Donkey Kong Country Returns and Tropical Freeze, this track has a more cheerful, calypso-style atmosphere than the original OST. It fits the image well and pays homage while adding a personal touch! You can easily imagine playing as DK on a tropical beach.",
            "title12": "Pokémon games, especially the 3rd and 4th generations, are a cherished childhood memory. To pay tribute to the 4th generation, I composed a Latin-style track that closely resembles the music from that era. I used almost the same instruments as the game to give the composition that original Nintendo DS feel. Many instruments \"converse\" with each other, which is typical of Pokémon city themes like Jubilife City! This track is sunnier, and you can imagine it as an alternative theme for Sunyshore City. Following the Pokémon tradition, I also created a modern remake, titled \"Spotimon (Radiant Jade Version)\".",
            "title13": "This is the modernized, remastered version of \"Spotimon (Jade Version),\" featuring more realistic instruments compared to the original DS soundfonts! You can easily imagine this remake on the Switch.",
            "title14": "A typical DnB track from the PS1/PS2 racing game era. The synth-heavy main melody makes it feel more like a futuristic game than a classic racing title. The strong and frantic percussion rhythm is ideal for a space racing game! The track's spacey, floating feel is conveyed through heavily reverberated and ethereal pads.",
            "title15": "A track designed to evoke a mysterious and slightly eerie atmosphere, perfect for a haunted mansion or a spooky level in a video game.",
            "title16": "A DnB track created with organic instruments, serving as a transition between older racing games that used DnB and recent titles with live instrumentation, like Mario Kart 8 and World, which were recorded with tons of musicians! This song is also designed as an infinite loop with different parts and has a distinct jazz-fusion feel, inspired by Mario Kart and other artists.",
            "title17": "Waltzes are a popular choice for underwater themes in Nintendo games, especially in Mario and Pokémon titles. This waltz pays homage to all those underwater themes, particularly the ones from Mario on the Wii. To enhance immersion, wave sounds have been added! The composition is an infinite loop with two parts that flow seamlessly into each other.",
            "title18": "A track with a jazzy, mysterious, and cinematic feel, setting a calm and chilling atmosphere.",
            "title19": "A jazz-infused cinematic piece that creates a mysterious and dark mood.",
            "title20": "An atmospheric and chill cinematic track perfect for a late-night drive or a mysterious getaway scene.",
            "title21": "A cool, jazzy, and cinematic track featuring Rhodes piano and siren-like synth melodies, creating a mysterious yet chill vibe.",
            "ds-track1": "First exclusive preview of Dream Season.",
            "ds-track2": "Second exclusive preview.",
            "ds-track3": "Third exclusive preview.",
            "title22": "A desert theme for a sunny adventure.",
            "title23": "The sequel to the race, even more frantic.",
            "title24": "Western atmosphere on the west coast.",
            "title25": "Hit the snowy slopes with this track.",
            "title26": "An alternative and nostalgic version.",
            "title27": "An epic battle theme.",
            "title28": "Explore the depths with this aquatic theme.",
            "title29": "A mysterious theme for dark caves.",
            "title30": "A Frutiger Aero composition reminiscent of menu tracks from 7th generation consoles. It incorporates both synthetic and organic instruments (with a deliberately artificial timbre), like a blend of the optimistic future envisioned by the Frutiger Aero movement with organic elements representing the present.",
            "beat1": "A powerful trap production in the style of Zaytoven."
        },

        // Daily Bonus (EN)
        dailyBonus: "Daily Bonus: +{count} coin(s)! {streak}-day streak.",
        dailyBonusUnlock: "Day 7 Bonus! You've unlocked the track: {title}",
        dailyBonusAllTracksUnlocked: "Congratulations! You have unlocked all exclusive tracks!",
        dailyBonusFinalTheme: "Thank you for your loyalty!",
        dailyBonusTitle: "Daily Bonus",
        day: "Day",
        specialReward: "Special",
        claimBonus: "Claim Bonus",
        dailyBonusStreakText: "Come back tomorrow to continue your streak!",
        dailyBonusStartText: "Log in every day to earn rewards!",
        dailyBonusNextRewardSpecial: "Come back tomorrow for the special reward!",
        dailyBonusAvailable: "A daily reward is waiting for you!",
        dailyBonusAlreadyClaimed: "See you tomorrow!",
        dailyBonusReceived: "Received:",
        dailyBonusCoins: "Coins",
        dailyBonusStreak: "Streak:",
        dailyBonusToWin: "To win:",
        dailyBonusExclusiveTrack: "Exclusive Track",

        // NEW: Desktop warning for mobile view
        desktopWarningTitle: "Mobile Mode Activated",
        desktopWarningMessage1: "This view is optimized for mobile devices and touch controls.",
        desktopWarningMessage2: "You may get stuck if you are using a computer.",
        desktopWarningCTA: "Enlarge your browser window to switch back to desktop mode for the best experience.",
        upcomingTitle: "Upcoming Release",
        upcomingBadge: "Coming Soon",
        upcomingDesc: "Get ready for a new musical adventure in the desert! This track with retro and catchy sounds will transport you to a classic platform game level.",
        comingSoon: "Coming Soon",

        // New keys
        display: "Display",
        playlistChillName: "Chill Game Music",
        playlistChillSubtitle: "Custom Selection",
        playlistFrutigerName: "Frutiger Aero",
        playlistFrutigerSubtitle: "Instrumental Beats",
        claim: "Claim",
        bonusClaimed: "Bonus claimed",
        viewDesktop: "Desktop Mode",
        viewMobile: "Mobile Mode",
    }
};
